Repository Gozargah/Marzban, pull requests merged in 2024-09, with the labels that each got.

#1209 Hide obfuscated quic for clash-meta and sing-box
  app/subscription/clash.py
  app/subscription/singbox.py
Labels: P2, C: B-Sub, S: Review, T: Bug Fix

#1264 Feature -> Random username generator added
  app/dashboard/src/components/UserDialog.tsx
Labels: T: Feature, C: Frontend, P1, S: Review

#1242 feat: Add node selection for logs in CoreSettingsModal.tsx
  app/dashboard/src/components/CoreSettingsModal.tsx
  app/dashboard/src/index.scss
Labels: T: Feature, C: Frontend, P1, S: Review

#1266 Dublicate hosts - Order Hosts - OnlineBadge Refactor
  app/dashboard/src/components/HostsDialog.tsx
  app/dashboard/src/components/OnlineBadge.tsx
Labels: T: Feature, C: Frontend, P1, S: Review

#1298 Bug -> node dropdown & node status badge
  app/dashboard/build/404.html
  app/dashboard/build/assets/index.aa165fd5.js
  app/dashboard/build/assets/index.e7b79829.js
  app/dashboard/build/assets/vendor.26b78958.js
  app/dashboard/build/index.html
  app/dashboard/build/locales/en.json
  app/dashboard/build/locales/fa.json
  app/dashboard/build/locales/ru.json
  app/dashboard/build/locales/zh.json
  app/dashboard/public/locales/en.json
  app/dashboard/public/locales/fa.json
  app/dashboard/public/locales/ru.json
  app/dashboard/public/locales/zh.json
  app/dashboard/src/components/CoreSettingsModal.tsx
  app/dashboard/src/components/NodeModalStatusBadge.tsx
  app/dashboard/src/components/NodesModal.tsx
Labels: C: Frontend, T: Bug Fix
