Repository Gozargah/Marzban, pull requests merged in 2024-12, with the labels that each got.

#1187 feat: Add migration to correct last_status_change for expired users
  app/db/migrations/versions/54c4b8c525fc_last_status_change_for_expired_users.py
Labels: P2, DB, Review, Bug Fix

#1474 fix: multiple heads error
  app/db/migrations/versions/be0c5f840473_fix_multiple_heads_error.py
Labels: DB, Bug Fix

#1475 fix: path and host not sended in ws
  app/subscription/v2ray.py
Labels: Core, Bug Fix

#1476 fix: xhttp extra in v2ray links
  app/subscription/v2ray.py
  app/xray/config.py
Labels: Core, Bug Fix

#1494 Host order
  README-fa.md
  README-ru.md
  README-zh-cn.md
  README.md
  app/db/crud.py
  app/db/migrations/versions/4eb0a0eb835f_reformat_hosts.py
  app/db/models.py
  app/dependencies.py
  app/models/host.py
  app/models/node.py
  app/models/proxy.py
  app/routers/__init__.py
  app/routers/host.py
  app/routers/node.py
  app/routers/system.py
  app/subscription/share.py
  app/xray/__init__.py
  app/xray/config.py
Labels: Backend, API, Refactor

#1496 fix(admin): record admin usage
  app/jobs/record_usages.py
Labels: Bug Fix

#1498 fix(admin): record admin usage
  app/jobs/record_usages.py
Labels: Bug Fix

#1495 Migrate to Pydantic V2
  app/db/crud.py
  app/dependencies.py
  app/jobs/remove_expired_users.py
  app/jobs/review_users.py
  app/models/admin.py
  app/models/node.py
  app/models/proxy.py
  app/models/user.py
  app/models/user_template.py
  app/routers/subscription.py
  app/routers/user.py
  app/subscription/clash.py
  app/subscription/share.py
  app/subscription/singbox.py
  app/subscription/v2ray.py
  app/telegram/handlers/admin.py
  app/telegram/handlers/user.py
  app/telegram/utils/shared.py
  app/utils/helpers.py
  app/utils/notification.py
  app/xray/operations.py
  cli/subscription.py
  requirements.txt
  xray_api/types/account.py
Labels: Backend, API

#1500 Migrate to SQLAlchemy 2.0
  app/db/base.py
  app/db/migrations/versions/07f9bbb3db4e_user_last_status_change.py
  app/db/migrations/versions/08b381fc1bc7_update_shadowsocks_method.py
  app/db/migrations/versions/54c4b8c525fc_last_status_change_for_expired_users.py
  app/db/migrations/versions/8e849e06f131_proxy_table.py
  app/db/migrations/versions/dd725e4d3628_fix_mysql_collations.py
  app/db/migrations/versions/fad8b1997c3a_case_insensitive_username.py
  app/xray/config.py
  requirements.txt
Labels: Backend, DB

#1501 fix value error
  app/models/user.py
Labels: Bug Fix

#1503 Fix bugs
  app/jobs/record_usages.py
  app/utils/notification.py
Labels: DB, Bug Fix

#1512 fix: error when sending reports for autodelete
  app/db/crud.py
  app/jobs/remove_expired_users.py
Labels: Bug Fix

#1516 feat: Add use sni as host
  app/dashboard/public/statics/locales/en.json
  app/dashboard/public/statics/locales/fa.json
  app/dashboard/public/statics/locales/ru.json
  app/dashboard/public/statics/locales/zh.json
  app/dashboard/src/components/HostsDialog.tsx
  app/db/crud.py
  app/db/migrations/versions/2b231de97dc3_add_use_sni_as_host_to_hosts.py
  app/db/models.py
  app/models/proxy.py
  app/subscription/share.py
  app/xray/__init__.py
Labels: Backend, DB

#1517 don't send `keepAlivePeriod` if it not in the config
  app/subscription/v2ray.py
Labels: Core

#1520 fix(cli): error when get reseted usage
  app/db/models.py
  cli/admin.py
Labels: Cli, Bug Fix

#1523 remove execution_options when recording usages
  app/jobs/record_usages.py
Labels: DB, Bug Fix

#1524 fix: float node coefficient
  app/jobs/record_usages.py
Labels: DB, Bug Fix

#1502 refactor(user): change user expire to datetime
  app/db/crud.py
  app/db/migrations/versions/f2b9caa23e16_change_expire_to_datetime.py
  app/db/models.py
  app/dependencies.py
  app/discord/handlers/report.py
  app/jobs/record_usages.py
  app/jobs/review_users.py
  app/models/user.py
  app/routers/user.py
  app/subscription/share.py
  app/telegram/handlers/admin.py
  app/telegram/handlers/report.py
  app/utils/helpers.py
  app/utils/notification.py
  app/utils/report.py
Labels: Backend, API, DB

#1530 feat(cli): Add users usage to `admin list` command
  cli/admin.py
Labels: Cli

#1541 fix: float bug when creating users and showing float data
  app/db/models.py
  app/models/admin.py
  app/models/user.py
  requirements.txt
Labels: Backend, Bug Fix
