Repository Gozargah/Marzban, pull requests merged in 2024-11, with the labels that each got.

#1409 fix(clash): wrong smux option
  app/subscription/clash.py
Labels: Subscription, Bug Fix

#1416 feat(tgbot): add Bulk action
  app/telegram/handlers/admin.py
  app/telegram/utils/keyboard.py
  app/telegram/utils/shared.py
Labels: TgBot

#1420 Next user planning
  app/db/__init__.py
  app/db/crud.py
  app/db/migrations/versions/c3cd674b9bcd_added_next_plan_for_user.py
  app/db/models.py
  app/discord/__init__.py
  app/discord/handlers/report.py
  app/jobs/review_users.py
  app/models/user.py
  app/routers/user.py
  app/telegram/__init__.py
  app/telegram/handlers/report.py
  app/utils/notification.py
  app/utils/report.py
Labels: Feature, Backend, API

#1422 fix(subscription): only save vpn app user-agents
  app/routers/subscription.py
Labels: Subscription

#1429 fix(admin): users_usage crash on migrations
  app/db/migrations/versions/b25e7e6be241_added_users_usage_to_admin.py
Labels: DB, Bug Fix

#1445 feat(api): Add counter for all user status to `/system`
  app/db/crud.py
  app/models/system.py
  app/routers/system.py
Labels: API

#1390 Bump python, small image size, close python CVE, add new flag UVICORN_SSL_CA_TYPE
  .dockerignore
  .env.example
  Dockerfile
  README-fa.md
  README-ru.md
  README-zh-cn.md
  README.md
  config.py
  main.py
  requirements.txt
Labels: Backend, Review

#1453 fix(db): error when counting online users in mysql
  app/db/crud.py
Labels: DB, Bug Fix

#1448 feat(admin): admin usage log
  app/db/crud.py
  app/db/migrations/versions/d0a3960f5dad_usagelog_table_for_admin.py
  app/db/models.py
  app/models/admin.py
Labels: Backend, API

#1465 fix(tgbot): None type error when sending logs to channel
  app/telegram/handlers/admin.py
Labels: TgBot, Bug Fix

#1463 fix: incorrect status codes on the subscription page
  app/dependencies.py
Labels: Subscription

#1467 Xray update
  app/subscription/v2ray.py
  app/xray/config.py
Labels: Core
