Repository Gozargah/Marzban, pull requests merged in 2024-08, with the labels that each got.

#1204 some fix and sync with new xray version
  app/subscription/share.py
  app/subscription/singbox.py
  app/subscription/v2ray.py
  app/templates/v2ray/settings.json
  app/xray/config.py
  config.py
Labels: backend

#1219 fix(subscription): use deepcopy to avoid conflict
  app/subscription/singbox.py
  app/subscription/v2ray.py
Labels: backend

#1224 fix(subscription): vless flow and tcp header fix
  app/subscription/v2ray.py
Labels: backend

#1237 increased fragment settings to 4 digits
  app/models/proxy.py
Labels: backend

#1164 fix: add doc to db crud
  app/db/crud.py
Labels: T: Doc, P3, C: B-DB, S: Review

#1206 Setup-CORS-policies
  .env.example
  app/__init__.py
  config.py
Labels: T: Feature, P2, C: B-Api, S: Review
