Repository Gozargah/Marzban, pull requests merged in 2024-10, with the labels that each got.

#1302 feat(xray-core): new xray features
  app/dashboard/public/locales/en.json
  app/dashboard/public/locales/fa.json
  app/dashboard/public/locales/ru.json
  app/dashboard/public/locales/zh.json
  app/dashboard/src/components/HostsDialog.tsx
  app/db/crud.py
  app/db/migrations/versions/a9cfd5611a82_add_noise_settings.py
  app/db/models.py
  app/models/proxy.py
  app/subscription/clash.py
  app/subscription/share.py
  app/subscription/singbox.py
  app/subscription/v2ray.py
  app/xray/__init__.py
  app/xray/config.py
Labels: C: Backend, P2, C: B-Sub, S: In Progress

#1225 Respect User Xray Policies
  app/xray/config.py
Labels: T: Feature, C: B-Core, S: Review

#1382 Remove deprecated splithttp settings
  app/subscription/v2ray.py
  app/xray/config.py
Labels: Core, Subscription

#1385 remove fastapi_responses, add manual additional responses docs
  app/__init__.py
  app/routers/admin.py
  app/routers/core.py
  app/routers/node.py
  app/routers/system.py
  app/routers/user.py
  app/utils/responses.py
  requirements.txt
Labels: Doc, Backend, API

#1381 feat(webhook): send multiple webhook for user usages
  .env.example
  app/db/crud.py
  app/db/migrations/versions/21226bc711ac_add_threshold_to_notificationreminder.py
  app/db/models.py
  app/jobs/review_users.py
  app/utils/report.py
  config.py
Labels: Feature, Backend, Review
