Repository Gozargah/Marzban, pull requests merged in 2025-02, with the labels that each got.

#1643 Add AddNodeModal Component, Enhance General Settings, and Introduce Page Header and Statistics Components
  app/dashboard/package-lock.json
  app/dashboard/package.json
  app/dashboard/pnpm-lock.yaml
  app/dashboard/public/statics/locales/en.json
  app/dashboard/public/statics/locales/fa.json
  app/dashboard/public/statics/locales/ru.json
  app/dashboard/public/statics/locales/zh.json
  app/dashboard/src/components/Tabs.tsx
  app/dashboard/src/components/UsersStatistics.tsx
  app/dashboard/src/components/charts/statistics-chart.tsx
  app/dashboard/src/components/dialogs/AddNodeModal.tsx
  app/dashboard/src/components/page-header.tsx
  app/dashboard/src/components/settings/CoreSettings.tsx
  app/dashboard/src/components/settings/GeneralSettings.tsx
  app/dashboard/src/components/statistics/Statistics.tsx
  app/dashboard/src/components/theme-provider.tsx
  app/dashboard/src/components/ui/chart.tsx
  app/dashboard/src/components/users-table/users-table.tsx
  app/dashboard/src/index.css
  app/dashboard/src/lib/menu-list.ts
  app/dashboard/src/pages/_dashboard._index.tsx
  app/dashboard/src/pages/_dashboard.nodes.tsx
  app/dashboard/src/pages/_dashboard.settings.tsx
  app/dashboard/src/pages/_dashboard.statistics.tsx
  app/dashboard/src/router.tsx
Labels: Frontend, v1

#1649 Record_node_usages task hangs due to lack of correct timeout handling in gRPC streaming
  xray_api/stats.py
Labels: Backend, Review, Bug Fix

#1648 fix: UI improvements and added Hosts page with validation
  app/dashboard/package.json
  app/dashboard/pnpm-lock.yaml
  app/dashboard/public/statics/locales/en.json
  app/dashboard/public/statics/locales/fa.json
  app/dashboard/public/statics/locales/ru.json
  app/dashboard/public/statics/locales/zh.json
  app/dashboard/src/components/charts/AreaCostumeChart.tsx
  app/dashboard/src/components/charts/CostumeBarChart.tsx
  app/dashboard/src/components/charts/PieCostumeChart.tsx
  app/dashboard/src/components/charts/TimeSelector.tsx
  app/dashboard/src/components/charts/statistics-chart.tsx
  app/dashboard/src/components/dialogs/AddHostModal.tsx
  app/dashboard/src/components/hosts/HostForm.tsx
  app/dashboard/src/components/hosts/Hosts.tsx
  app/dashboard/src/components/page-header.tsx
  app/dashboard/src/components/settings/Logs.tsx
  app/dashboard/src/components/statistics/Statistics.tsx
  app/dashboard/src/components/ui/accordion.tsx
  app/dashboard/src/components/ui/form.tsx
  app/dashboard/src/components/ui/toggle-group.tsx
  app/dashboard/src/components/ui/toggle.tsx
  app/dashboard/src/index.css
  app/dashboard/src/pages/_dashboard.hosts.tsx
  app/dashboard/src/pages/_dashboard.settings._index.tsx
  app/dashboard/src/pages/_dashboard.settings.core.tsx
  app/dashboard/src/router.tsx
  app/dashboard/tailwind.config.js
Labels: Frontend, v1

#1647 Allow hostname to be used as UVICORN_HOST
  main.py
Labels: Backend, Review

#1668 added group topics to telegram bot
  .env.example
  app/telegram/handlers/report.py
  config.py
Labels: TgBot

#1674 fix(node): add usage_coefficient when creating node
  app/db/crud.py
Labels: Bug Fix

#1652 feat: dynamic data integration for statistics header, Xray core config, and logs
  app/dashboard/package-lock.json
  app/dashboard/package.json
  app/dashboard/pnpm-lock.yaml
  app/dashboard/public/statics/locales/en.json
  app/dashboard/public/statics/locales/fa.json
  app/dashboard/public/statics/locales/ru.json
  app/dashboard/public/statics/locales/zh.json
  app/dashboard/src/components/dialogs/AddHostModal.tsx
  app/dashboard/src/components/hosts/HostForm.tsx
  app/dashboard/src/components/hosts/Hosts.tsx
  app/dashboard/src/components/hosts/SortableHost.tsx
  app/dashboard/src/components/settings/Logs.tsx
  app/dashboard/src/components/statistics/Statistics.tsx
  app/dashboard/src/components/ui/hover-card.tsx
  app/dashboard/src/pages/_dashboard.hosts.tsx
  app/dashboard/src/pages/_dashboard.settings.core.tsx
  app/dashboard/src/pages/_dashboard.statistics.tsx
  app/dashboard/src/utils/formatByte.ts
Labels: Frontend, v1
