Repository Gozargah/Marzban, pull requests merged in 2025-07, with the labels that each got.

#1870 refactor: enum array
  app/db/compiles_types.py
  app/db/migrations/versions/d607d3ca5246_change_enumarray_to_string.py
  app/db/models.py
Labels: DB, Refactor, v1

#1867 feat(telegram): complete tetegram bot functionality
  app/models/settings.py
  app/models/validators.py
  app/operation/user_template.py
  app/telegram/__init__.py
  app/telegram/handlers/__init__.py
  app/telegram/handlers/admin/__init__.py
  app/telegram/handlers/admin/bulk_actions.py
  app/telegram/handlers/admin/main_menu.py
  app/telegram/handlers/admin/user.py
  app/telegram/handlers/base.py
  app/telegram/keyboards/admin.py
  app/telegram/keyboards/bulk_actions.py
  app/telegram/keyboards/user.py
  app/telegram/utils/forms.py
  app/telegram/utils/texts.py
Labels: TgBot, v1

#1900 Advance search
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/common/AdminsSelector.tsx
  dashboard/src/components/common/GroupsSelector.tsx
  dashboard/src/components/dialogs/AdvanceSearchModal.tsx
  dashboard/src/components/users/filters.tsx
  dashboard/src/components/users/users-table.tsx
Labels: Feature, Frontend, v1

#1902 Fix UI bugs
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/dialogs/UserTemplateModal.tsx
Labels: Feature, Frontend, v1
