Repository Gozargah/Marzban, pull requests merged in 2025-03, with the labels that each got.

#1673 fix: Disable openapi schema
  app/__init__.py
Labels: Backend

#1684 feat(hosts): add transports settings to hosts
  .env.example
  app/db/migrations/versions/95da30deba8d_change_fragments_and_noise_from_regex_.py
  app/db/migrations/versions/9aa6559916be_drop_mux_enable_column_in_hosts_table.py
  app/db/migrations/versions/eaa9f30f983e_add_headers_and_transports_settings_.py
  app/db/models.py
  app/models/host.py
  app/subscription/__init__.py
  app/subscription/base.py
  app/subscription/clash.py
  app/subscription/share.py
  app/subscription/singbox.py
  app/subscription/v2ray.py
  app/templates/clash/README.md
  app/templates/clash/settings.yml
  app/templates/mux/default.json
  app/templates/singbox/README.md
  app/templates/singbox/settings.json
  app/templates/v2ray/README.md
  app/templates/v2ray/settings.json
  app/xray/__init__.py
  app/xray/config.py
  config.py
Labels: Feature, Backend, Subscription, v1

#1695 refactor: reality settings key handling
  app/utils/crypto.py
  app/xray/config.py
Labels: Backend, Core, Refactor

#1700 feat(hosts): add `{USAGE_PERCENTAGE}` variable
  app/subscription/share.py
Labels: Feature, Subscription

#1702 feat(admin): add sub_template, sub_domain, profile_title and support_url
  app/db/crud.py
  app/db/migrations/versions/0b62f893092b_add_sub_template_sub_domain_profile_.py
  app/db/models.py
  app/models/admin.py
  app/models/user.py
  app/routers/subscription.py
Labels: Backend, API, v1

#1703 feat: support `gui for singbox` app
  app/routers/subscription.py
Labels: Subscription

#1707 refactor(subscription): Improve subscription router code organization and performance
  app/routers/subscription.py
Labels: Refactor, v1

#1713 feat: Implement Group-Based Access Control System
  app/backend/__init__.py
  app/backend/xray.py
  app/db/crud.py
  app/db/migrations/versions/16e19723febc_migrate_to_groups.py
  app/db/migrations/versions/1dc5f89b706a_drop_proxies_table.py
  app/db/migrations/versions/3b59f3680c90_add_groups_table_and_add_proxy_settings_column_to_users_table.py.py
  app/db/migrations/versions/cb99b515fbab_drop_excloud_inbounds_and_template_.py
  app/db/migrations/versions/db68f8d3d40b_move_data_from_proxies_table_to_users_.py
  app/db/models.py
  app/dependencies.py
  app/models/group.py
  app/models/proxy.py
  app/models/user.py
  app/models/user_template.py
  app/node/__init__.py
  app/node/user.py
  app/operation/group.py
  app/operation/user.py
  app/operation/user_template.py
  app/routers/__init__.py
  app/routers/admin.py
  app/routers/group.py
  app/routers/user.py
  app/routers/user_template.py
  app/subscription/share.py
  app/telegram/handlers/admin.py
  app/utils/report.py
Labels: Feature, Backend, API, v1

#1714 feat(notification): Added notification for host operations
  .env.example
  app/models/host.py
  app/notification/__init__.py
  app/notification/client.py
  app/notification/discord/__init__.py
  app/notification/discord/host.py
  app/notification/telegram/__init__.py
  app/notification/telegram/host.py
  app/operation/host.py
  app/telegram/__init__.py
  config.py
  pyproject.toml
  uv.lock
Labels: Backend, v1

#1717 feat: Add PostgreSQL Database Support
  app/db/migrations/versions/0d22271ee06e_make_data_limit_and_expire_duration_.py
  app/db/migrations/versions/305943d779c4_add_h3_to_alpn_enum.py
  app/db/migrations/versions/3b59f3680c90_add_groups_table_and_add_proxy_settings_column_to_users_table.py.py
  app/db/migrations/versions/54c4b8c525fc_last_status_change_for_expired_users.py
  app/db/migrations/versions/c41c441de44c_gozargah_node.py
  app/db/migrations/versions/c5c734bd3da2_add_priority_to_proxy_hosts.py
  pyproject.toml
  uv.lock
Labels: Feature, DB, v1

#1724 refactor: Migrate to SQLAlchemy v2 with Async Support
  app/backend/__init__.py
  app/db/__init__.py
  app/db/base.py
  app/db/crud.py
  app/db/migrations/env.py
  app/db/migrations/versions/16e19723febc_migrate_to_groups.py
  app/db/migrations/versions/1f6e978be88e_migrate_to_sqlalchemy_v2.py
  app/db/migrations/versions/db68f8d3d40b_move_data_from_proxies_table_to_users_.py
  app/db/models.py
  app/jobs/node_checker.py
  app/jobs/record_usages.py
  app/jobs/review_users.py
  app/models/admin.py
  app/models/user.py
  app/node/__init__.py
  app/operation/__init__.py
  app/operation/admin.py
  app/operation/group.py
  app/operation/host.py
  app/operation/node.py
  app/operation/subscription.py
  app/operation/system.py
  app/operation/user.py
  app/operation/user_template.py
  app/routers/admin.py
  app/routers/authentication.py
  app/routers/backend.py
  app/routers/group.py
  app/routers/home.py
  app/routers/host.py
  app/routers/node.py
  app/routers/subscription.py
  app/routers/system.py
  app/routers/user.py
  app/routers/user_template.py
  app/subscription/share.py
  app/utils/jwt.py
  app/utils/report.py
  app/utils/store.py
  config.py
  pyproject.toml
  uv.lock
Labels: DB, Refactor, v1

#1729 refactor(cli): Add Admin Management Interface to Marzban CLI
  Makefile
  app/db/crud.py
  app/models/admin.py
  app/operation/admin.py
  cli/__init__.py
  cli/admin.py
  cli/style.tcss
  cli/subscription.py
  cli/user.py
  cli/utils.py
  marzban-cli.py
  pyproject.toml
  uv.lock
Labels: Feature, Cli, Refactor, v1

#1731 feat: Added notification for user operations
  app/db/crud.py
  app/jobs/dependencies.py
  app/jobs/remove_expired_users.py
  app/jobs/review_users.py
  app/notification/__init__.py
  app/notification/discord/__init__.py
  app/notification/discord/admin.py
  app/notification/discord/colors.py
  app/notification/discord/group.py
  app/notification/discord/host.py
  app/notification/discord/node.py
  app/notification/discord/user.py
  app/notification/discord/user_template.py
  app/notification/telegram/__init__.py
  app/notification/telegram/admin.py
  app/notification/telegram/group.py
  app/notification/telegram/host.py
  app/notification/telegram/node.py
  app/notification/telegram/user.py
  app/notification/telegram/user_template.py
  app/operation/user.py
Labels: Feature, Backend, v1

#1720 feat: Refactor XRay Config Processing for Better Maintainability and Multiple Fallback Support
  .env.example
  app/backend/xray.py
  config.py
Labels: Core, Refactor, v1

#1733 feat(hosts): Add Host Status Management System
  .env.example
  app/backend/__init__.py
  app/db/comiles_types.py
  app/db/crud.py
  app/db/migrations/versions/35760ebfabd2_add_status_to_hosts.py
  app/db/models.py
  app/models/host.py
  app/models/validators.py
  app/operation/host.py
  app/routers/host.py
  app/subscription/share.py
  config.py
Labels: Feature, Subscription, v1

#1737 refactor(subscription): extract common network and TLS settings logic
  app/subscription/v2ray.py
Labels: Subscription, Refactor
