Repository Gozargah/Marzban, pull requests merged in 2025-04, with the labels that each got.

#1743 feat: Implement XHTTP upload/download splitting
  app/backend/__init__.py
  app/backend/xray.py
  app/models/host.py
  app/operation/host.py
  app/subscription/share.py
  app/subscription/v2ray.py
  app/subscription/xray.py
Labels: Feature, v1

#1740 Next FrontEnd Hosts
  app/dashboard/orval.config.ts
  app/dashboard/package-lock.json
  app/dashboard/package.json
  app/dashboard/pnpm-lock.yaml
  app/dashboard/public/statics/locales/en.json
  app/dashboard/public/statics/locales/fa.json
  app/dashboard/public/statics/locales/ru.json
  app/dashboard/public/statics/locales/zh.json
  app/dashboard/src/components/dialogs/AddHostModal.tsx
  app/dashboard/src/components/dialogs/HostModal.tsx
  app/dashboard/src/components/hosts/HostForm.tsx
  app/dashboard/src/components/hosts/Hosts.tsx
  app/dashboard/src/components/hosts/SortableHost.tsx
  app/dashboard/src/components/ui/checkbox.tsx
  app/dashboard/src/components/ui/form.tsx
  app/dashboard/src/components/ui/input.tsx
  app/dashboard/src/components/ui/popover.tsx
  app/dashboard/src/components/ui/tabs.tsx
  app/dashboard/src/service/api/index.ts
Labels: Frontend, Refactor, v1

#1750 feat: Add comprehensive test suite for API endpoints and database operations
  .dockerignore
  .github/workflows/test-database-migrations.yml
  .gitignore
  Makefile
  app/backend/__init__.py
  app/db/crud.py
  app/db/models.py
  app/jobs/send_notifications.py
  app/operation/host.py
  app/operation/user.py
  app/routers/backend.py
  app/utils/store.py
  config.py
  pyproject.toml
  pytest.ini
  tests/api/__init__.py
  tests/api/test_admin.py
  tests/api/test_backend.py
  tests/api/test_group.py
  tests/api/test_host.py
  tests/api/test_user.py
  tests/api/test_user_template.py
  tests/conftest.py
  uv.lock
Labels: Backend, API, v1

#1749 feat: groups CRUD page added
  .gitignore
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/dialogs/GroupModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/groups/Group.tsx
  dashboard/src/components/groups/Groups.tsx
  dashboard/src/components/hosts/HostForm.tsx
  dashboard/src/components/hosts/Hosts.tsx
  dashboard/src/components/hosts/SortableHost.tsx
  dashboard/src/components/layout/sidebar.tsx
  dashboard/src/components/ui/command.tsx
  dashboard/src/pages/_dashboard.groups.tsx
  dashboard/src/pages/_dashboard.hosts.tsx
  dashboard/src/pages/_dashboard.settings.core.tsx
  dashboard/src/pages/_dashboard.templates.groups.tsx
  dashboard/src/pages/_dashboard.templates.tsx
  dashboard/src/router.tsx
Labels: Feature, Refactor, v1

#1751 feat: Nodes page enchaned CRUD of each node certificate settings in page
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/dialogs/AddNodeModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/layout/sidebar.tsx
  dashboard/src/components/nodes/Node.tsx
  dashboard/src/components/nodes/NodeStatusBadge.tsx
  dashboard/src/components/nodes/Nodes.tsx
  dashboard/src/components/nodes/NodesSection.tsx
  dashboard/src/pages/_dashboard.nodes.tsx
  dashboard/src/pages/_dashboard.templates.tsx
Labels: Frontend, v1

#1752 feat: separate nodes backend config
  .env.example
  .github/workflows/test-database-migrations.yml
  app/backend/__init__.py
  app/backend/abstract_backend.py
  app/backend/hosts.py
  app/backend/xray.py
  app/db/crud.py
  app/db/migrations/versions/4e66033a2b9b_separate_nodes_config.py
  app/db/models.py
  app/jobs/reset_user_data_usage.py
  app/models/backend.py
  app/models/core.py
  app/models/node.py
  app/node/__init__.py
  app/operation/__init__.py
  app/operation/admin.py
  app/operation/backend.py
  app/operation/group.py
  app/operation/host.py
  app/operation/node.py
  app/operation/system.py
  app/operation/user.py
  app/routers/backend.py
  app/routers/node.py
  app/routers/system.py
  app/subscription/share.py
  app/telegram/handlers/admin.py
  app/utils/store.py
  config.py
  pyproject.toml
  tests/api/test_backend.py
  uv.lock
Labels: Feature, Backend, Core, v1

#1754 fix: refactor bugs on hosts page | refetch groups after any actions | admins page skeleton added
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/Footer.tsx
  dashboard/src/components/Statistics.tsx
  dashboard/src/components/admins/AdminsTable.tsx
  dashboard/src/components/dialogs/AdminModal.tsx
  dashboard/src/components/dialogs/GroupModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/groups/Group.tsx
  dashboard/src/components/groups/Groups.tsx
  dashboard/src/components/layout/sidebar.tsx
  dashboard/src/components/theme-toggle.tsx
  dashboard/src/components/ui/switch.tsx
  dashboard/src/components/users-table/columns.tsx
  dashboard/src/components/users-table/data-table.tsx
  dashboard/src/components/users-table/filters.tsx
  dashboard/src/components/users-table/users-table.tsx
  dashboard/src/contexts/DashboardContext.tsx
  dashboard/src/contexts/NodesContext.tsx
  dashboard/src/pages/_dashboard._index.tsx
  dashboard/src/pages/_dashboard.admins.tsx
  dashboard/src/pages/_dashboard.settings.core.tsx
  dashboard/src/pages/login.tsx
  dashboard/src/router.tsx
  dashboard/src/service/api/index.ts
  dashboard/src/types/ProxyHosts.ts
  dashboard/src/types/User.ts
Labels: Feature, Frontend, Bug Fix, v1

#1755 feat: add node stats table
  .env.example
  app/__init__.py
  app/db/crud.py
  app/db/migrations/versions/58a5b64175a8_node_stats_table.py
  app/db/models.py
  app/jobs/node_checker.py
  app/jobs/node_stats.py
  app/jobs/record_usages.py
  app/jobs/remove_expired_users.py
  app/jobs/reset_user_data_usage.py
  app/jobs/review_users.py
  app/jobs/send_notifications.py
  app/models/stats.py
  app/models/validators.py
  app/operation/node.py
  app/routers/node.py
  app/utils/system.py
  config.py
Labels: Feature, API, DB, v1

#1758 Bug Fixes and Improvements in Host Management
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/hosts/HostForm.tsx
  dashboard/src/components/hosts/Hosts.tsx
  dashboard/src/components/users-table/filters.tsx
  dashboard/src/index.css
  dashboard/src/pages/_dashboard.hosts.tsx
  path/to/components/HostModal.tsx
Labels: Frontend, Bug Fix, v1

#1392 Doc: update response documentation models
  app/routers/admin.py
  app/utils/responses.py
Labels: Doc, API, In Progress

#1767 feat: new telegram bot
  .env.example
  app/db/crud.py
  app/operation/group.py
  app/routers/admin.py
  app/routers/authentication.py
  app/routers/system.py
  app/telegram/__init__.py
  app/telegram/handlers/__init__.py
  app/telegram/handlers/admin.py
  app/telegram/handlers/admin/__init__.py
  app/telegram/handlers/admin/admin.py
  app/telegram/handlers/admin/confirm_action.py
  app/telegram/handlers/admin/user.py
  app/telegram/handlers/base.py
  app/telegram/handlers/error_handler.py
  app/telegram/handlers/report.py
  app/telegram/handlers/user.py
  app/telegram/keyboards/__init__.py
  app/telegram/keyboards/admin.py
  app/telegram/keyboards/base.py
  app/telegram/keyboards/confim_action.py
  app/telegram/keyboards/group.py
  app/telegram/keyboards/user.py
  app/telegram/middlewares/__init__.py
  app/telegram/middlewares/acl.py
  app/telegram/utils/__init__.py
  app/telegram/utils/custom_filters.py
  app/telegram/utils/filters.py
  app/telegram/utils/forms.py
  app/telegram/utils/keyboard.py
  app/telegram/utils/shared.py
  app/telegram/utils/texts.py
  app/utils/logger.py
  config.py
  pyproject.toml
  uv.lock
Labels: TgBot, Refactor, v1

#1776 Nodes and Core Configs Page Modified
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/dialogs/CoreConfigModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/nodes/Nodes.tsx
  dashboard/src/components/settings/Core.tsx
  dashboard/src/components/settings/Cores.tsx
  dashboard/src/pages/_dashboard.settings.core.tsx
  dashboard/src/service/api/index.ts
Labels: Feature, Frontend, v1

#1777 feat(frontend): admins
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/AdminStatistics.tsx
  dashboard/src/components/admins/AdminsTable.tsx
  dashboard/src/components/admins/columns.tsx
  dashboard/src/components/admins/data-table.tsx
  dashboard/src/components/admins/filters.tsx
  dashboard/src/components/dialogs/AdminModal.tsx
  dashboard/src/pages/_dashboard.admins.tsx
Labels: Frontend, v1
