Repository Gozargah/Marzban, pull requests merged in 2025-01, with the labels that each got.

#1554 remove: host from headers in ws for v2ray-json format
  app/subscription/v2ray.py
Labels: Backend, Subscription

#1557 feat(xray): add hex type support for noise
  app/models/proxy.py
Labels: Core

#1559 remove: v2ray links from UserResponse
  app/dependencies.py
  app/models/user.py
  app/telegram/handlers/admin.py
Labels: Backend, API

#1561 set online counter to 2 minutes
  app/db/crud.py
  app/routers/system.py
Labels: API

#1562 fix: datetime bug
  app/db/migrations/versions/f2b9caa23e16_change_expire_to_datetime.py
  app/jobs/review_users.py
Labels: Backend, DB

#1573 fix: send delete reports
  app/routers/user.py
Labels: Bug Fix

#1574 fix: clash tcp http config
  app/subscription/clash.py
Labels: Subscription, Bug Fix

#1595 fix: migrations conflicts
  app/db/migrations/versions/7a93bcd44713_.py
Labels: DB

#1599 feat(admin): add ability to disable admin account
  app/db/crud.py
  app/db/migrations/versions/931ed40d6eec_add_is_disabled_to_admins_table.py
  app/db/models.py
  app/dependencies.py
  app/models/admin.py
  app/routers/admin.py
  cli/admin.py
Labels: Feature, Backend, API, DB

#1596 feat: nextPlan -> userTemplate relation
  app/db/crud.py
  app/db/migrations/versions/68edca039166_next_plan_to_template_relation.py
  app/db/models.py
  app/models/user.py
  app/routers/user.py
Labels: DB

#1612 remove: xhttp default values
  app/subscription/v2ray.py
  app/xray/config.py
Labels: Core

#1613 fix: xhttp extra in v2ray links
  app/subscription/v2ray.py
Labels: Core, Bug Fix

#1627 xhttp: add support for `scStreamUpServerSecs`
  app/subscription/v2ray.py
  app/xray/config.py
Labels: Backend, Core
