Repository Gozargah/Marzban, pull requests merged in 2025-05, with the labels that each got.

#1788 Implement User Table, Modals, and Enhance Dashboard Pages
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/UsersStatistics.tsx
  dashboard/src/components/charts/AreaCostumeChart.tsx
  dashboard/src/components/charts/CostumeBarChart.tsx
  dashboard/src/components/charts/PieCostumeChart.tsx
  dashboard/src/components/common/TimeRangeSelector.tsx
  dashboard/src/components/dialogs/GroupModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/groups/Group.tsx
  dashboard/src/components/hosts/Hosts.tsx
  dashboard/src/components/statistics/Statistics.tsx
  dashboard/src/components/ui/calendar.tsx
  dashboard/src/components/ui/checkbox.tsx
  dashboard/src/components/ui/popover.tsx
  dashboard/src/components/ui/tabs.tsx
  dashboard/src/components/users-table/columns.tsx
  dashboard/src/components/users-table/data-table.tsx
  dashboard/src/components/users-table/filters.tsx
  dashboard/src/components/users-table/users-table.tsx
  dashboard/src/pages/_dashboard._index.tsx
  dashboard/src/pages/_dashboard.hosts.tsx
  dashboard/src/pages/_dashboard.statistics.tsx
  dashboard/src/service/api/index.ts
  dashboard/src/utils/formatByte.ts
Labels: Feature, Frontend, Bug Fix, v1

#1789 User Dialog On Hold Duration and Loading State Improvements
  dashboard/public/statics/locales/fa.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/users-table/columns.tsx
  dashboard/src/components/users-table/data-table.tsx
Labels: Frontend, Bug Fix, v1

#1790 Add themes customization and improvements on user dialog
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/App.tsx
  dashboard/src/components/StatusBadge.tsx
  dashboard/src/components/color-theme-provider.tsx
  dashboard/src/components/dialogs/CoreConfigModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/layout/sidebar.tsx
  dashboard/src/components/theme-provider.tsx
  dashboard/src/components/ui/radio-group.tsx
  dashboard/src/components/users-table/columns.tsx
  dashboard/src/components/users-table/data-table.tsx
  dashboard/src/pages/_dashboard.theme.tsx
  dashboard/src/router.tsx
Labels: Feature, Frontend, v1

#1791 User Templates
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/dialogs/UserTemplateModal.tsx
  dashboard/src/components/templates/GroupsFilter.tsx
  dashboard/src/components/templates/UserTemplate.tsx
  dashboard/src/pages/_dashboard.templates._index.tsx
Labels: Feature, Frontend, v1

#1792 feat(Settings): create settings table and migrate with .env
  .env.example
  Makefile
  app/db/crud.py
  app/db/migrations/versions/9af04c077ede_init_settings.py
  app/db/models.py
  app/jobs/review_users.py
  app/jobs/send_notifications.py
  app/models/admin.py
  app/models/settings.py
  app/models/validators.py
  app/notification/__init__.py
  app/notification/client.py
  app/notification/discord/admin.py
  app/notification/discord/core.py
  app/notification/discord/group.py
  app/notification/discord/host.py
  app/notification/discord/node.py
  app/notification/discord/user.py
  app/notification/discord/user_template.py
  app/notification/telegram/admin.py
  app/notification/telegram/core.py
  app/notification/telegram/group.py
  app/notification/telegram/host.py
  app/notification/telegram/node.py
  app/notification/telegram/user.py
  app/notification/telegram/user_template.py
  app/notification/webhook/__init__.py
  app/operation/settings.py
  app/operation/subscription.py
  app/operation/user.py
  app/routers/__init__.py
  app/routers/settings.py
  app/routers/subscription.py
  app/settings/__init__.py
  app/subscription/share.py
  tests/api/__init__.py
  tests/api/conftest.py
  tests/api/test_admin.py
  tests/api/test_core.py
  tests/api/test_group.py
  tests/api/test_host.py
  tests/api/test_user.py
  tests/api/test_user_template.py
Labels: Feature, Backend, API, v1

#1796 Modal UI Fixes & Core Updates
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/CopyButton.tsx
  dashboard/src/components/UsersStatistics.tsx
  dashboard/src/components/dialogs/CoreConfigModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/layout/sidebar.tsx
  dashboard/src/pages/_dashboard._index.tsx
  dashboard/src/pages/_dashboard.nodes.cores.tsx
  dashboard/src/pages/_dashboard.settings._index.tsx
  dashboard/src/router.tsx
  dashboard/src/service/api/index.ts
Labels: Feature, Frontend, Bug Fix, v1

#1781 feat(TgBot): Create User and Main Menu
  app/telegram/handlers/__init__.py
  app/telegram/handlers/admin/__init__.py
  app/telegram/handlers/admin/admin.py
  app/telegram/handlers/admin/confirm_action.py
  app/telegram/handlers/admin/main_menu.py
  app/telegram/handlers/admin/user.py
  app/telegram/handlers/base.py
  app/telegram/handlers/error_handler.py
  app/telegram/keyboards/admin.py
  app/telegram/keyboards/base.py
  app/telegram/keyboards/group.py
  app/telegram/keyboards/user.py
  app/telegram/utils/forms.py
  app/telegram/utils/shared.py
  app/telegram/utils/texts.py
  app/utils/helpers.py
Labels: TgBot, v1

#1798 fix: add periodic reset startegy
  dashboard/src/components/dialogs/UserModal.tsx
Labels: Frontend, Bug Fix, v1

#1799 fix: add periodic reset strategy and resolve API & translation file bugs
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/service/api/index.ts
Labels: Frontend, Bug Fix, v1

#1795 Todo fix bugs
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/admins/AdminsTable.tsx
  dashboard/src/components/admins/columns.tsx
  dashboard/src/components/admins/data-table.tsx
  dashboard/src/components/dialogs/AdminModal.tsx
  dashboard/src/components/dialogs/CoreConfigModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/dialogs/UserTemplateModal.tsx
  dashboard/src/components/templates/UserTemplate.tsx
  dashboard/src/pages/_dashboard.admins.tsx
  dashboard/src/service/api/index.ts
Labels: Frontend, Bug Fix, v1

#1804 Fix bugs
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/dialogs/AdminModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/dialogs/UserTemplateModal.tsx
  dashboard/src/components/templates/GroupsFilter.tsx
  dashboard/src/hooks/use-clipboard.ts
  dashboard/src/pages/_dashboard.settings._index.tsx
  dashboard/src/pages/_dashboard.settings.tsx
  dashboard/src/pages/_dashboard.statistics.tsx
Labels: Frontend, Bug Fix, v1

#1806 Add User Management Features and Fix Core Config Modal
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/ActionButtons.tsx
  dashboard/src/components/dialogs/CoreConfigModal.tsx
Labels: Feature, Frontend, Bug Fix, v1

#1810 Todo fix UI
  dashboard/public/statics/locales/en.json
  dashboard/public/statics/locales/fa.json
  dashboard/public/statics/locales/ru.json
  dashboard/public/statics/locales/zh.json
  dashboard/src/components/admins/columns.tsx
  dashboard/src/components/dialogs/AdminModal.tsx
  dashboard/src/components/dialogs/CoreConfigModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/dialogs/UserTemplateModal.tsx
  dashboard/src/components/layout/sidebar.tsx
  dashboard/src/components/nav-main.tsx
  dashboard/src/components/page-header.tsx
  dashboard/src/components/templates/UserTemplate.tsx
  dashboard/src/pages/_dashboard.templates.tsx
  dashboard/src/service/api/index.ts
Labels: Frontend, Bug Fix, v1

#1822 Fix modals
  dashboard/src/components/dialogs/AdminModal.tsx
  dashboard/src/components/dialogs/CoreConfigModal.tsx
  dashboard/src/components/dialogs/GroupModal.tsx
  dashboard/src/components/dialogs/HostModal.tsx
  dashboard/src/components/dialogs/NodeModal.tsx
  dashboard/src/components/dialogs/UserModal.tsx
  dashboard/src/components/dialogs/UserTemplateModal.tsx
  dashboard/src/components/ui/form.tsx
  dashboard/src/components/ui/input.tsx
Labels: Frontend, Bug Fix, v1
